#include <string.h>

typedef enum {
    DISCHARGING,
    CRITICAL,
    SHUTDOWN,
    CHARGING,
    LOW,
    FULL,
} {'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]}_State;

{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]}_State current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = DISCHARGING;

void handle_event_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]}(const char* event) {
    switch (current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]}) {
        case DISCHARGING:
            if (strcmp(event, "plug_in") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = CHARGING;
            if (strcmp(event, "alert_low") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = LOW;
            break;
        case CRITICAL:
            if (strcmp(event, "plug_in") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = CHARGING;
            if (strcmp(event, "power_off") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = SHUTDOWN;
            break;
        case SHUTDOWN:
            break;
        case CHARGING:
            if (strcmp(event, "charge") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = FULL;
            break;
        case LOW:
            if (strcmp(event, "plug_in") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = CHARGING;
            if (strcmp(event, "alert_critical") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = CRITICAL;
            break;
        case FULL:
            if (strcmp(event, "unplug") == 0) current_state_{'name': 'Battery', 'states': ['DISCHARGING', 'CRITICAL', 'SHUTDOWN', 'CHARGING', 'LOW', 'FULL'], 'events': ['plug_in', 'unplug', 'drain', 'charge', 'alert_low', 'alert_critical', 'power_off'], 'transitions': [('CHARGING', 'charge', 'FULL'), ('CRITICAL', 'plug_in', 'CHARGING'), ('LOW', 'plug_in', 'CHARGING'), ('LOW', 'alert_critical', 'CRITICAL'), ('DISCHARGING', 'plug_in', 'CHARGING'), ('DISCHARGING', 'alert_low', 'LOW'), ('CRITICAL', 'power_off', 'SHUTDOWN'), ('FULL', 'unplug', 'DISCHARGING')]} = DISCHARGING;
            break;
    }
}
