#include <string.h>

typedef enum {
    CAM_IDLE,
    OFF,
    SNAPSHOT,
    STREAMING,
    RECORDING,
} {'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]}_State;

{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]}_State current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = CAM_IDLE;

void handle_event_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]}(const char* event) {
    switch (current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]}) {
        case CAM_IDLE:
            if (strcmp(event, "start_stream") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = STREAMING;
            if (strcmp(event, "start_record") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = RECORDING;
            if (strcmp(event, "take_photo") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = SNAPSHOT;
            if (strcmp(event, "shutdown") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = OFF;
            break;
        case OFF:
            break;
        case SNAPSHOT:
            if (strcmp(event, "resume") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = RECORDING;
            break;
        case STREAMING:
            if (strcmp(event, "stop") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = CAM_IDLE;
            break;
        case RECORDING:
            if (strcmp(event, "take_photo") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = SNAPSHOT;
            if (strcmp(event, "pause") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = SNAPSHOT;
            if (strcmp(event, "stop") == 0) current_state_{'name': 'Camera', 'states': ['CAM_IDLE', 'OFF', 'SNAPSHOT', 'STREAMING', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('CAM_IDLE', 'start_stream', 'STREAMING'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'shutdown', 'OFF'), ('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'pause', 'SNAPSHOT'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'stop', 'CAM_IDLE')]} = CAM_IDLE;
            break;
    }
}
