#include <string.h>

typedef enum {
    CONNECTED,
    DISCONNECTED,
    DEGRADED,
    ERROR,
    CONNECTING,
} {'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]}_State;

{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]}_State current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = CONNECTED;

void handle_event_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]}(const char* event) {
    switch (current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]}) {
        case CONNECTED:
            if (strcmp(event, "lost_connection") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = CONNECTING;
            if (strcmp(event, "degrade") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = DEGRADED;
            break;
        case DISCONNECTED:
            if (strcmp(event, "initiate") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = CONNECTING;
            if (strcmp(event, "fail") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = ERROR;
            break;
        case DEGRADED:
            if (strcmp(event, "recover") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = CONNECTED;
            if (strcmp(event, "lost_connection") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = CONNECTING;
            break;
        case ERROR:
            if (strcmp(event, "retry") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = DISCONNECTED;
            break;
        case CONNECTING:
            if (strcmp(event, "fail") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = DISCONNECTED;
            if (strcmp(event, "success") == 0) current_state_{'name': 'Communication', 'states': ['CONNECTED', 'DISCONNECTED', 'DEGRADED', 'ERROR', 'CONNECTING'], 'events': ['initiate', 'success', 'fail', 'lost_connection', 'recover', 'degrade', 'retry'], 'transitions': [('DISCONNECTED', 'initiate', 'CONNECTING'), ('DEGRADED', 'recover', 'CONNECTED'), ('DEGRADED', 'lost_connection', 'CONNECTING'), ('ERROR', 'retry', 'DISCONNECTED'), ('CONNECTING', 'fail', 'DISCONNECTED'), ('CONNECTING', 'success', 'CONNECTED'), ('DISCONNECTED', 'fail', 'ERROR'), ('CONNECTED', 'lost_connection', 'CONNECTING'), ('CONNECTED', 'degrade', 'DEGRADED')]} = CONNECTED;
            break;
    }
}
