#include <string.h>

typedef enum {
    SEARCHING,
    UNAVAILABLE,
    LOST_FIX,
    REACQUIRING,
    LOCKED,
} {'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]}_State;

{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]}_State current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = SEARCHING;

void handle_event_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]}(const char* event) {
    switch (current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]}) {
        case SEARCHING:
            if (strcmp(event, "gps_fix") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = LOCKED;
            break;
        case UNAVAILABLE:
            if (strcmp(event, "start_search") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = SEARCHING;
            break;
        case LOST_FIX:
            if (strcmp(event, "reacquire") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = REACQUIRING;
            break;
        case REACQUIRING:
            if (strcmp(event, "gps_fix") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = LOCKED;
            if (strcmp(event, "lose_fix") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = LOST_FIX;
            break;
        case LOCKED:
            if (strcmp(event, "lose_fix") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = LOST_FIX;
            if (strcmp(event, "drift_detected") == 0) current_state_{'name': 'Localization', 'states': ['SEARCHING', 'UNAVAILABLE', 'LOST_FIX', 'REACQUIRING', 'LOCKED'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOST_FIX', 'reacquire', 'REACQUIRING'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX')]} = SEARCHING;
            break;
    }
}
