#include <string.h>

typedef enum {
    PLANNING,
    ABORTED,
    IN_PROGRESS,
    COMPLETED,
    READY,
    PAUSED,
} {'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]}_State;

{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]}_State current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = PLANNING;

void handle_event_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]}(const char* event) {
    switch (current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]}) {
        case PLANNING:
            if (strcmp(event, "plan_ready") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = READY;
            break;
        case ABORTED:
            if (strcmp(event, "plan_ready") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = PLANNING;
            break;
        case IN_PROGRESS:
            if (strcmp(event, "abort") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = ABORTED;
            if (strcmp(event, "complete") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = COMPLETED;
            if (strcmp(event, "pause") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = PAUSED;
            break;
        case COMPLETED:
            break;
        case READY:
            if (strcmp(event, "start") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = IN_PROGRESS;
            break;
        case PAUSED:
            if (strcmp(event, "resume") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = IN_PROGRESS;
            if (strcmp(event, "abort") == 0) current_state_{'name': 'MissionControl', 'states': ['PLANNING', 'ABORTED', 'IN_PROGRESS', 'COMPLETED', 'READY', 'PAUSED'], 'events': ['plan_ready', 'start', 'pause', 'resume', 'abort', 'complete'], 'transitions': [('PAUSED', 'resume', 'IN_PROGRESS'), ('IN_PROGRESS', 'abort', 'ABORTED'), ('READY', 'start', 'IN_PROGRESS'), ('IN_PROGRESS', 'complete', 'COMPLETED'), ('IN_PROGRESS', 'pause', 'PAUSED'), ('PAUSED', 'abort', 'ABORTED'), ('ABORTED', 'plan_ready', 'PLANNING'), ('PLANNING', 'plan_ready', 'READY')]} = ABORTED;
            break;
    }
}
