#include <string.h>

typedef enum {
    ASCENDING,
    TAKEOFF,
    DESCENDING,
    LANDING,
    HOLDING,
    IDLE,
    CRUISE,
} {'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]}_State;

{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]}_State current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = ASCENDING;

void handle_event_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]}(const char* event) {
    switch (current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]}) {
        case ASCENDING:
            if (strcmp(event, "reach_altitude") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = CRUISE;
            break;
        case TAKEOFF:
            if (strcmp(event, "reach_altitude") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = ASCENDING;
            break;
        case DESCENDING:
            if (strcmp(event, "begin_landing") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = LANDING;
            break;
        case LANDING:
            if (strcmp(event, "landed") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = IDLE;
            break;
        case HOLDING:
            if (strcmp(event, "resume_cruise") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = CRUISE;
            break;
        case IDLE:
            if (strcmp(event, "start_mission") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = TAKEOFF;
            break;
        case CRUISE:
            if (strcmp(event, "begin_descent") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = DESCENDING;
            if (strcmp(event, "hold_position") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = HOLDING;
            if (strcmp(event, "emergency") == 0) current_state_{'name': 'Navigation', 'states': ['ASCENDING', 'TAKEOFF', 'DESCENDING', 'LANDING', 'HOLDING', 'IDLE', 'CRUISE'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('IDLE', 'start_mission', 'TAKEOFF'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('CRUISE', 'hold_position', 'HOLDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('CRUISE', 'emergency', 'DESCENDING'), ('ASCENDING', 'reach_altitude', 'CRUISE'), ('HOLDING', 'resume_cruise', 'CRUISE')]} = DESCENDING;
            break;
    }
}
