#include <string.h>

typedef enum {
    MOVING,
    ARRIVED,
    IDLE,
    AVOIDING_OBSTACLE,
    WAITING,
    ROUTE_PLANNING,
} {'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]}_State;

{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]}_State current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = MOVING;

void handle_event_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]}(const char* event) {
    switch (current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]}) {
        case MOVING:
            if (strcmp(event, "detect_obstacle") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = AVOIDING_OBSTACLE;
            if (strcmp(event, "route_lost") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = ROUTE_PLANNING;
            if (strcmp(event, "wait_command") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = WAITING;
            if (strcmp(event, "reach_destination") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = ARRIVED;
            break;
        case ARRIVED:
            if (strcmp(event, "continue") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = IDLE;
            break;
        case IDLE:
            if (strcmp(event, "start_route") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = ROUTE_PLANNING;
            break;
        case AVOIDING_OBSTACLE:
            if (strcmp(event, "obstacle_cleared") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = MOVING;
            break;
        case WAITING:
            if (strcmp(event, "continue") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = MOVING;
            break;
        case ROUTE_PLANNING:
            if (strcmp(event, "route_ready") == 0) current_state_{'name': 'Navigation', 'states': ['MOVING', 'ARRIVED', 'IDLE', 'AVOIDING_OBSTACLE', 'WAITING', 'ROUTE_PLANNING'], 'events': ['start_route', 'route_ready', 'begin_move', 'detect_obstacle', 'obstacle_cleared', 'wait_command', 'continue', 'reach_destination', 'route_lost'], 'transitions': [('MOVING', 'detect_obstacle', 'AVOIDING_OBSTACLE'), ('WAITING', 'continue', 'MOVING'), ('IDLE', 'start_route', 'ROUTE_PLANNING'), ('AVOIDING_OBSTACLE', 'obstacle_cleared', 'MOVING'), ('MOVING', 'route_lost', 'ROUTE_PLANNING'), ('ROUTE_PLANNING', 'route_ready', 'MOVING'), ('MOVING', 'wait_command', 'WAITING'), ('ARRIVED', 'continue', 'IDLE'), ('MOVING', 'reach_destination', 'ARRIVED')]} = MOVING;
            break;
    }
}
