#include <string.h>

typedef enum {
    CLEAR_PATH,
    EVADING,
    PATH_RECOVERED,
    OBSTACLE_DETECTED,
    STUCK,
    OVERRIDE,
} {'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]}_State;

{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]}_State current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = CLEAR_PATH;

void handle_event_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]}(const char* event) {
    switch (current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]}) {
        case CLEAR_PATH:
            if (strcmp(event, "detect") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = OBSTACLE_DETECTED;
            break;
        case EVADING:
            if (strcmp(event, "recover") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = PATH_RECOVERED;
            if (strcmp(event, "stuck") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = STUCK;
            break;
        case PATH_RECOVERED:
            if (strcmp(event, "detect") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = OBSTACLE_DETECTED;
            if (strcmp(event, "recover") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = CLEAR_PATH;
            break;
        case OBSTACLE_DETECTED:
            if (strcmp(event, "evade") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = EVADING;
            break;
        case STUCK:
            if (strcmp(event, "override") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = OVERRIDE;
            break;
        case OVERRIDE:
            if (strcmp(event, "manual_clear") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['CLEAR_PATH', 'EVADING', 'PATH_RECOVERED', 'OBSTACLE_DETECTED', 'STUCK', 'OVERRIDE'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED'), ('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('EVADING', 'stuck', 'STUCK'), ('STUCK', 'override', 'OVERRIDE'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH')]} = PATH_RECOVERED;
            break;
    }
}
