#include <string.h>

typedef enum {
    LOADING,
    IN_TRANSIT,
    DELIVERED,
    LOADED,
    UNLOADING,
    EMPTY,
} {'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]}_State;

{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]}_State current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = LOADING;

void handle_event_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]}(const char* event) {
    switch (current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]}) {
        case LOADING:
            if (strcmp(event, "fail") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = DELIVERED;
            if (strcmp(event, "finish_loading") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = LOADED;
            break;
        case IN_TRANSIT:
            if (strcmp(event, "begin_unloading") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = UNLOADING;
            break;
        case DELIVERED:
            if (strcmp(event, "finish_unloading") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = EMPTY;
            break;
        case LOADED:
            if (strcmp(event, "start_transit") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = IN_TRANSIT;
            break;
        case UNLOADING:
            if (strcmp(event, "finish_unloading") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = DELIVERED;
            if (strcmp(event, "fail") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = DELIVERED;
            break;
        case EMPTY:
            if (strcmp(event, "begin_loading") == 0) current_state_{'name': 'PayloadHandling', 'states': ['LOADING', 'IN_TRANSIT', 'DELIVERED', 'LOADED', 'UNLOADING', 'EMPTY'], 'events': ['begin_loading', 'finish_loading', 'start_transit', 'begin_unloading', 'finish_unloading', 'fail'], 'transitions': [('UNLOADING', 'finish_unloading', 'DELIVERED'), ('EMPTY', 'begin_loading', 'LOADING'), ('LOADING', 'fail', 'DELIVERED'), ('IN_TRANSIT', 'begin_unloading', 'UNLOADING'), ('LOADED', 'start_transit', 'IN_TRANSIT'), ('LOADING', 'finish_loading', 'LOADED'), ('UNLOADING', 'fail', 'DELIVERED'), ('DELIVERED', 'finish_unloading', 'EMPTY')]} = LOADING;
            break;
    }
}
