#include <string.h>

typedef enum {
    RECOVERY,
    EMERGENCY_STOP,
    HAZARD_DETECTED,
    OBSTACLE_ALERT,
    NORMAL,
    MANUAL_OVERRIDE,
} {'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]}_State;

{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]}_State current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = RECOVERY;

void handle_event_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]}(const char* event) {
    switch (current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]}) {
        case RECOVERY:
            if (strcmp(event, "resume") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = NORMAL;
            break;
        case EMERGENCY_STOP:
            if (strcmp(event, "reset") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = RECOVERY;
            break;
        case HAZARD_DETECTED:
            if (strcmp(event, "emergency_stop") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = EMERGENCY_STOP;
            break;
        case OBSTACLE_ALERT:
            if (strcmp(event, "resume") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = NORMAL;
            if (strcmp(event, "emergency_stop") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = EMERGENCY_STOP;
            break;
        case NORMAL:
            if (strcmp(event, "hazard") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = HAZARD_DETECTED;
            if (strcmp(event, "override") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = MANUAL_OVERRIDE;
            if (strcmp(event, "detect_obstacle") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = OBSTACLE_ALERT;
            if (strcmp(event, "emergency_stop") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = EMERGENCY_STOP;
            break;
        case MANUAL_OVERRIDE:
            if (strcmp(event, "reset") == 0) current_state_{'name': 'Safety', 'states': ['RECOVERY', 'EMERGENCY_STOP', 'HAZARD_DETECTED', 'OBSTACLE_ALERT', 'NORMAL', 'MANUAL_OVERRIDE'], 'events': ['detect_obstacle', 'emergency_stop', 'hazard', 'reset', 'resume', 'override'], 'transitions': [('OBSTACLE_ALERT', 'resume', 'NORMAL'), ('NORMAL', 'hazard', 'HAZARD_DETECTED'), ('RECOVERY', 'resume', 'NORMAL'), ('NORMAL', 'override', 'MANUAL_OVERRIDE'), ('MANUAL_OVERRIDE', 'reset', 'NORMAL'), ('OBSTACLE_ALERT', 'emergency_stop', 'EMERGENCY_STOP'), ('EMERGENCY_STOP', 'reset', 'RECOVERY'), ('HAZARD_DETECTED', 'emergency_stop', 'EMERGENCY_STOP'), ('NORMAL', 'detect_obstacle', 'OBSTACLE_ALERT'), ('NORMAL', 'emergency_stop', 'EMERGENCY_STOP')]} = NORMAL;
            break;
    }
}
