#include <string.h>

typedef enum {
    STREAMING,
    SNAPSHOT,
    CAM_IDLE,
    OFF,
    RECORDING,
} {'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]}_State;

{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]}_State current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = STREAMING;

void handle_event_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]}(const char* event) {
    switch (current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]}) {
        case STREAMING:
            if (strcmp(event, "stop") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = CAM_IDLE;
            break;
        case SNAPSHOT:
            if (strcmp(event, "resume") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = RECORDING;
            break;
        case CAM_IDLE:
            if (strcmp(event, "start_record") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = RECORDING;
            if (strcmp(event, "take_photo") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = SNAPSHOT;
            if (strcmp(event, "shutdown") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = OFF;
            if (strcmp(event, "start_stream") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = STREAMING;
            break;
        case OFF:
            break;
        case RECORDING:
            if (strcmp(event, "take_photo") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = SNAPSHOT;
            if (strcmp(event, "stop") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = CAM_IDLE;
            if (strcmp(event, "pause") == 0) current_state_{'name': 'Camera', 'states': ['STREAMING', 'SNAPSHOT', 'CAM_IDLE', 'OFF', 'RECORDING'], 'events': ['start_record', 'start_stream', 'take_photo', 'pause', 'resume', 'stop', 'shutdown'], 'transitions': [('RECORDING', 'take_photo', 'SNAPSHOT'), ('RECORDING', 'stop', 'CAM_IDLE'), ('SNAPSHOT', 'resume', 'RECORDING'), ('RECORDING', 'pause', 'SNAPSHOT'), ('CAM_IDLE', 'start_record', 'RECORDING'), ('STREAMING', 'stop', 'CAM_IDLE'), ('CAM_IDLE', 'take_photo', 'SNAPSHOT'), ('CAM_IDLE', 'shutdown', 'OFF'), ('CAM_IDLE', 'start_stream', 'STREAMING')]} = SNAPSHOT;
            break;
    }
}
