#include <string.h>

typedef enum {
    REACQUIRING,
    LOST_FIX,
    UNAVAILABLE,
    LOCKED,
    SEARCHING,
} {'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]}_State;

{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]}_State current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = REACQUIRING;

void handle_event_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]}(const char* event) {
    switch (current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]}) {
        case REACQUIRING:
            if (strcmp(event, "lose_fix") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = LOST_FIX;
            if (strcmp(event, "gps_fix") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = LOCKED;
            break;
        case LOST_FIX:
            if (strcmp(event, "reacquire") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = REACQUIRING;
            break;
        case UNAVAILABLE:
            if (strcmp(event, "start_search") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = SEARCHING;
            break;
        case LOCKED:
            if (strcmp(event, "lose_fix") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = LOST_FIX;
            if (strcmp(event, "drift_detected") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = SEARCHING;
            break;
        case SEARCHING:
            if (strcmp(event, "gps_fix") == 0) current_state_{'name': 'Localization', 'states': ['REACQUIRING', 'LOST_FIX', 'UNAVAILABLE', 'LOCKED', 'SEARCHING'], 'events': ['start_search', 'gps_fix', 'drift_detected', 'lose_fix', 'reacquire'], 'transitions': [('LOST_FIX', 'reacquire', 'REACQUIRING'), ('SEARCHING', 'gps_fix', 'LOCKED'), ('LOCKED', 'lose_fix', 'LOST_FIX'), ('LOCKED', 'drift_detected', 'SEARCHING'), ('REACQUIRING', 'lose_fix', 'LOST_FIX'), ('REACQUIRING', 'gps_fix', 'LOCKED'), ('UNAVAILABLE', 'start_search', 'SEARCHING')]} = LOCKED;
            break;
    }
}
