#include <string.h>

typedef enum {
    LANDING,
    HOLDING,
    ASCENDING,
    TAKEOFF,
    IDLE,
    CRUISE,
    DESCENDING,
} {'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]}_State;

{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]}_State current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = LANDING;

void handle_event_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]}(const char* event) {
    switch (current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]}) {
        case LANDING:
            if (strcmp(event, "landed") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = IDLE;
            break;
        case HOLDING:
            if (strcmp(event, "resume_cruise") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = CRUISE;
            break;
        case ASCENDING:
            if (strcmp(event, "reach_altitude") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = CRUISE;
            break;
        case TAKEOFF:
            if (strcmp(event, "reach_altitude") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = ASCENDING;
            break;
        case IDLE:
            if (strcmp(event, "start_mission") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = TAKEOFF;
            break;
        case CRUISE:
            if (strcmp(event, "begin_descent") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = DESCENDING;
            if (strcmp(event, "hold_position") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = HOLDING;
            if (strcmp(event, "emergency") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = DESCENDING;
            break;
        case DESCENDING:
            if (strcmp(event, "begin_landing") == 0) current_state_{'name': 'Navigation', 'states': ['LANDING', 'HOLDING', 'ASCENDING', 'TAKEOFF', 'IDLE', 'CRUISE', 'DESCENDING'], 'events': ['start_mission', 'reach_altitude', 'hold_position', 'resume_cruise', 'begin_descent', 'begin_landing', 'landed', 'emergency'], 'transitions': [('ASCENDING', 'reach_altitude', 'CRUISE'), ('CRUISE', 'begin_descent', 'DESCENDING'), ('DESCENDING', 'begin_landing', 'LANDING'), ('TAKEOFF', 'reach_altitude', 'ASCENDING'), ('LANDING', 'landed', 'IDLE'), ('CRUISE', 'hold_position', 'HOLDING'), ('HOLDING', 'resume_cruise', 'CRUISE'), ('IDLE', 'start_mission', 'TAKEOFF'), ('CRUISE', 'emergency', 'DESCENDING')]} = LANDING;
            break;
    }
}
