#include <string.h>

typedef enum {
    OBSTACLE_DETECTED,
    CLEAR_PATH,
    STUCK,
    OVERRIDE,
    EVADING,
    PATH_RECOVERED,
} {'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]}_State;

{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]}_State current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = OBSTACLE_DETECTED;

void handle_event_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]}(const char* event) {
    switch (current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]}) {
        case OBSTACLE_DETECTED:
            if (strcmp(event, "evade") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = EVADING;
            break;
        case CLEAR_PATH:
            if (strcmp(event, "detect") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = OBSTACLE_DETECTED;
            break;
        case STUCK:
            if (strcmp(event, "override") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = OVERRIDE;
            break;
        case OVERRIDE:
            if (strcmp(event, "manual_clear") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = PATH_RECOVERED;
            break;
        case EVADING:
            if (strcmp(event, "stuck") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = STUCK;
            if (strcmp(event, "recover") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = PATH_RECOVERED;
            break;
        case PATH_RECOVERED:
            if (strcmp(event, "detect") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = OBSTACLE_DETECTED;
            if (strcmp(event, "recover") == 0) current_state_{'name': 'ObstacleAvoidance', 'states': ['OBSTACLE_DETECTED', 'CLEAR_PATH', 'STUCK', 'OVERRIDE', 'EVADING', 'PATH_RECOVERED'], 'events': ['detect', 'evade', 'recover', 'stuck', 'override', 'manual_clear'], 'transitions': [('CLEAR_PATH', 'detect', 'OBSTACLE_DETECTED'), ('STUCK', 'override', 'OVERRIDE'), ('OBSTACLE_DETECTED', 'evade', 'EVADING'), ('EVADING', 'stuck', 'STUCK'), ('PATH_RECOVERED', 'detect', 'OBSTACLE_DETECTED'), ('PATH_RECOVERED', 'recover', 'CLEAR_PATH'), ('EVADING', 'recover', 'PATH_RECOVERED'), ('OVERRIDE', 'manual_clear', 'PATH_RECOVERED')]} = CLEAR_PATH;
            break;
    }
}
